"""add job search settings

Revision ID: 1ec2c965f6d1
Revises: 099ab433f5e1
Create Date: 2026-08-18 21:52:13.153843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec2c965f6d1'
down_revision: Union[str, Sequence[str], None] = '099ab433f5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_profiles',
        sa.Column(
            'max_job_age_hours',
            sa.Integer(),
            nullable=False,
            server_default='24'
        )
    )

    op.add_column(
        'user_profiles',
        sa.Column(
            'search_interval_minutes',
            sa.Integer(),
            nullable=False,
            server_default='30'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'search_interval_minutes')
    op.drop_column('user_profiles', 'max_job_age_hours')
    # ### end Alembic commands ###
