"""add search preferences

Revision ID: 272318e34f67
Revises: 6b2a3a1bce82
Create Date: 2026-08-18 19:13:22.658773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272318e34f67'
down_revision: Union[str, Sequence[str], None] = '6b2a3a1bce82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'user_profiles',
        sa.Column(
            'remote_preference',
            sa.String(length=50),
            nullable=True,
        ),
    )

    op.add_column(
        'user_profiles',
        sa.Column(
            'search_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),
        ),
    )

    op.add_column(
        'user_profiles',
        sa.Column(
            'max_notifications_per_day',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('50'),
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'max_notifications_per_day')
    op.drop_column('user_profiles', 'search_enabled')
    op.drop_column('user_profiles', 'remote_preference')
    # ### end Alembic commands ###
