"""add job matches

Revision ID: b7630ec21456
Revises: 1ec2c965f6d1
Create Date: 2026-08-22 20:33:43.968372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7630ec21456'
down_revision: Union[str, Sequence[str], None] = '1ec2c965f6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('skills_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('title_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('location_score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_profile_id'), 'job_matches', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_profile_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
