"""add telegram chat id

Revision ID: f634b8ed0eb0
Revises: b1ab850b7e75
Create Date: 2026-08-18 16:40:29.049800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f634b8ed0eb0'
down_revision: Union[str, Sequence[str], None] = 'b1ab850b7e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_user_profiles_telegram_chat_id'), 'user_profiles', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_telegram_chat_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'telegram_chat_id')
    # ### end Alembic commands ###
